---
title: "Adjusting crime statistics ranking" 
output: pdf_document 
---

## Notes 5/10/16

## 1. Simulation scheme 

For each city $i$ in a given year: 

- fix crime rate per person $ccp_i$ 
- compute expected number of crimes $\lambda_i=ccp_i \times size_i$ 
- sample $N_i\sim\mathcal{P}(\lambda_i)$ thus obtaining observation $n_i$ (as $size_i$ is large and $ccp_i$ is small, this is indeed equivalent to sample $\mathcal{B}(size_i,ccp_i)$) 
- compute observed crime rate $\hat{ccp}_i=n_i/size_i$
- smooth observed crime rate: $s_i$

__Remark:__ 

The variability due to small size is preserved, because $V(\hat{ccp})=V(N)/size^2=ccp\times size/size^2=ccp/size$.

Suppose for instance $ccp_1=ccp_2=0.01$, $size_1=100$ and $size_2=10^4$. Then $E[N_1]=V(N_1)=1$ and $E[n_2]=V(n_2)=100$. Therefore $V(\hat{ccp}_1)=1/100^2$ and $V(\hat{ccp}_2)=1/10^6$:

```{r}
ccp1=ccp2=0.01
size1=100
size2=10^4
s=matrix(rpois(n=size1*100,lambda=ccp1),ncol=100,nrow=size1)
l=matrix(rpois(n=size2*100,lambda=ccp2),ncol=100,nrow=size2)
var(apply(s,2,mean))
var(apply(l,2,mean))
```

## 2. Validation 

Compare $\sum_i (s_i-ccp_i)^2$ with $\sum_i (\hat{ccp}_i-ccp_i)^2$



## 30/11/16

## Another way to measure smoothing performance:
- Two Spearman's rank correlation tests to compare correlation between ranking of $\hat{cpp}$ and of $cpp$ and between ranking of $s$ and $cpp$.

## To do:
- Bibliographic research: how does official statistics deal with this small area - big variance problem? 
- If we want to establish list of most criminal cities: FDR.
- Spearman rank correlation for top lists from raw estimates vs adjusted.
- If we want to take into account the fact that biggest cities should be more criminal (more economic interests, density....), or at least that there is a linear relation between size and cpp, and other covariates: beta binomial regression and hierarchical empirial Bayes. 
- Mixture of Betas (See also Etienne's exercice?)
- James-Stein estimation (example of non-Bayesian point estimate shrinkage)
- Historical information: use rates from earlier years to estimate rates this year

